#
# Module manifest for module 'MSIXForcelets'
#
# Generated by: Andreas Nick
#
# Generated on: 2023/08/23
#

@{
    # Script module or binary module file associated with this manifest.
    RootModule = 'MSIXForcelets.psm1'

    # Version number of this module.
    ModuleVersion = '0.5.0'

    # ID used to uniquely identify this module
    GUID = '799e7b14-d939-43b3-845e-6cf1be49c36b'

    # Author of this module
    Author = 'Andreas Nick'

    # Copyright statement for this module
    Copyright = 'Copyright (c) 2020-2023 Andreas Nick'

    # Description of the functionality provided by this module
    Description = 'Framework for MSIX Packaging and PSF Injection'

    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = '5.0'

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData = @{
        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = @('powershell', 'MSIX', 'framework', 'PSF')

            # A URL to the license for this module.
            LicenseUri = 'https://www.nick-it.de'

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/AndreasNick/MSIXForcelets'
            
            # A URL to an icon representing this module.
            IconUri = 'https://raw.githubusercontent.com/AndreasNick/MSIXForcelets/images/icon.png'

        }
    }
}